version: '3'

networks:
  laravel:

services:
  #PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html/electronic
    ports:
      - "9000:9000"
    networks:
      - laravel

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/electronic
      - ./nginx/default.conf/:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  #MySQL Service
  mysql:
    image: mysql:8.0.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: electronic
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-files/mysql:/var/lib/mysql
    networks:
      - laravel
